server:
  port: 8888

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: boot.spring.po

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myActiviti?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/process/
    history-level: full
  thymeleaf:
    mode: LEGACYHTML5

logging:
  config: classpath:log4j2.xml
  


